import localFont from "next/font/local";
import "./globals.css";
import { Navbar, Footer } from "./components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid lg:grid-cols-[1fr,5fr]">
          <div className="sticky top-0 lg:h-screen z-10">
            <Navbar />
          </div>
          <div className="mt-14 lg:mt-0 overflow-x-hidden">
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
